random_seed: 42
data:
  batch_size: 32
  num_workers: 12
  data_dir: ./preprocessed_data_predict/example
  filler_list: ./fp.list
eval:
  out_dir: ./predicted_data/example
  gpus: 1
  auto_select_gpus: true
  model_ckpt_path: ../../../grouping_prediction-lrec2022/prediction/git_predict_filledpauses_groups/exp/CSJ/ver220209/non_personalized/ckpt/epoch=31-step=59999.ckpt
model:
  netG:
    _target_: model_predict.BiLSTM
    embedding_dim: 1024
    hidden_dim: 1024
    num_layers: 1
    dropout: 0.0
    tagset_size: 14
