mode: batch
target: False
source: ./preprocessed_data/example/test.txt
text: 
speaker_id: 

result_path: ./output/example/result

preprocess_config: ./preprocessed_data/example/preprocess.yaml
model_config: 
train_config: 

pitch_control: 1.0
energy_control: 1.0
duration_control: 1.0