hydra:
  run:
    dir: .

random_seed: 42
data:
  batch_size: 32
  num_workers: 12
  data_dir: test_data/utokyo_naist_lecture/speaker1_uno/ver220211
  filler_list: corpus/CSJ/filler_list.txt
eval:
  default_root_dir: exp/CSJ/ver211120_1
  out_dir: predicted_data/utokyo_naist_lecture/speaker1_uno/ver220211_pred
  gpus: 1
  auto_select_gpus: true
  checkpoint:
    step: 59999
