hydra:
  run:
    dir: .

defaults:
  - _self_
  - model: bilstm_bert

random_seed: 42
data:
  batch_size: 32
  num_workers: 12
  data_dir: ./predict_preprocessed_data/example
  filler_list: ./fp.list
eval:
  out_dir: ./predicted_data/example
  gpus: 1
  auto_select_gpus: true
  model_ckpt_path: 